version: '3'
services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cruddb2
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  node_app:
    image: marcosmonjes9919/trabajofinalpp1:3.0
    container_name: node-app-container
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
